# Generated by Django 4.2.1 on 2023-06-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_clothing_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accname', models.CharField(max_length=255)),
                ('accprice', models.IntegerField()),
            ],
        ),
    ]
