# Generated by Django 4.2.1 on 2023-06-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_acc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Top',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='item',
            new_name='Bottom',
        ),
        migrations.RenameField(
            model_name='acc',
            old_name='accname',
            new_name='itemname',
        ),
        migrations.RenameField(
            model_name='acc',
            old_name='accprice',
            new_name='price',
        ),
    ]
