# Generated by Django 4.2.1 on 2023-06-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_top_rename_item_bottom_rename_accname_acc_itemname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acc',
            name='item_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bottom',
            name='item_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='top',
            name='item_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
