# Generated by Django 4.2.1 on 2023-06-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_acc_item_id_bottom_item_id_top_item_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acc',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='bottom',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='top',
            name='item_id',
        ),
        migrations.AddField(
            model_name='acc',
            name='category',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='bottom',
            name='category',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='top',
            name='category',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
