# Generated by Django 4.2.1 on 2023-06-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_dress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acc',
            name='category',
            field=models.CharField(default='A', max_length=5),
        ),
        migrations.AlterField(
            model_name='acc',
            name='itemname',
            field=models.CharField(default='NEWACC', max_length=255),
        ),
        migrations.AlterField(
            model_name='acc',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bottom',
            name='category',
            field=models.CharField(default='B', max_length=5),
        ),
        migrations.AlterField(
            model_name='bottom',
            name='itemname',
            field=models.CharField(default='NEWBOTTOM', max_length=255),
        ),
        migrations.AlterField(
            model_name='bottom',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dress',
            name='category',
            field=models.CharField(default='D', max_length=5),
        ),
        migrations.AlterField(
            model_name='dress',
            name='itemname',
            field=models.CharField(default='NEWDRESS', max_length=255),
        ),
        migrations.AlterField(
            model_name='top',
            name='category',
            field=models.CharField(default='T', max_length=5),
        ),
        migrations.AlterField(
            model_name='top',
            name='itemname',
            field=models.CharField(default='NEWTOP', max_length=255),
        ),
        migrations.AlterField(
            model_name='top',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
