# Generated by Django 4.2.1 on 2023-06-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_acc_category_alter_acc_itemname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='top',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='people/'),
        ),
    ]
