# Generated by Django 4.2.1 on 2023-06-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_top_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='acc',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='people/'),
        ),
        migrations.AddField(
            model_name='bottom',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='people/'),
        ),
        migrations.AddField(
            model_name='dress',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='people/'),
        ),
    ]
