# Generated by Django 4.2.1 on 2023-06-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_acc_photo_alter_bottom_photo_alter_dress_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='top',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
