# Generated by Django 4.2.1 on 2023-06-13 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_top_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='acc',
            name='describe',
            field=models.CharField(default='des', max_length=255),
        ),
        migrations.AddField(
            model_name='bottom',
            name='describe',
            field=models.CharField(default='des', max_length=255),
        ),
        migrations.AddField(
            model_name='dress',
            name='describe',
            field=models.CharField(default='des', max_length=255),
        ),
        migrations.AddField(
            model_name='top',
            name='describe',
            field=models.CharField(default='des', max_length=255),
        ),
    ]
